### ISSUE TITLE
Mock Connection

### ISSUE THREAD

**Issue by sporto** [lpil/pgo#30]
I would like to put the connection in my application context e.g.

```gleam
pub type Context {
  Context(config: Config, static_directory: String, db_pool: pgo.Connection)
}
```

For unit testing, I want to create a fixture for the context. So I can test route handlers that expect a context.
e.g.

```gleam
pub fn fixture_context() -> Context {
  Context(static_directory: "", db_pool: pgo.mock_connection, config: config.fixture())
}
```

How could I do this? I wouldn't like to create a real DB connection for many unit tests. Just something that satisfies the `Connection` type.  
Could this lib provide a mock connection?

**Comment by sporto** [comment]
Yes, that was my idea, something that just panics if actually called.

Something like this I guess
```
@external(erlang, "rand", "uniform")
pub fn mock_connection() -> pgo.Connection
```

**Comment by lpil** [comment]
It should not, no. This library is an API client and unrelated to mocking or testing.

**Comment by dcrockwell** [comment]
We test the database using integration and e2e tests, however unit tests running against a real database is both time-intensive (tests run in minutes vs milliseconds) or requires a repository pattern that requires generating a squirrel function, then also writing a wrapper around it.

I think there's a strong use case for unit testing in isolation, and due to the large amount of tooling already built against pog, it seems that adding mocking over and over for every tool and implementation is begging for some kind of solution at the pog level.

I'm not suggesting adding mocking to pog directly, but providing a way to pass functions to pog that can intercept calls (for logging, mocking, or other reasons) seems reasonable.

**Comment by dcrockwell** [comment]
@lpil Are you open to a PR that shows a minimal interceptor pattern with zero breaking changes?
